name: deploy

on: [push]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      - name: Setting up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          check-latest: true

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache pnpm
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: cache-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Cache ~/.cache
        uses: actions/cache@v3
        id: cache-folder
        with:
          path: ~/.cache
          key: cache-folder-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE_FOLDER pnpm install

      - name: Generate
        run: pnpm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
